# Generated by Django 5.0.4 on 2024-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("description", models.TextField()),
                ("equipment_lot", models.CharField(max_length=100)),
                ("technician_name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
            ],
        ),
    ]
